### ISSUE TITLE
Issues when creating customize OCP route  for Turbonomic UI.

### ISSUE THREAD

**Issue by ngiii** [turbonomic/t8c-install#21]
I installed **Turbonomic 8.4.3** on AWS **ROSA** cluster. And I'm trying to follow this wiki [OCP Route for Turbonomic UI: manual](https://github.com/turbonomic/t8c-install/wiki/Platform-Provided-Ingress-&-OpenShift-Routes#ocp-routes-user-created---all-capabilities-turbo-832) to create my own route.

Here is my yaml
```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: test
  namespace: turbonomic
  labels:
    app.kubernetes.io/instance: xl-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    zone: internal
spec:
  host: turbo-test.automation.cloud.ibm.com
  to:
    kind: Service
    name: nginx
    weight: 100
  port:
    targetPort: http-nginx
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
```
But it doesn't work, when I visit https://turbo-test.automation.cloud.ibm.com,  there're two problems.
1. The browser will complains `connection is not secure`, the wiki mentions `You can leverage your own certificates, or use the default one on the OCP Router.`, I have ordered certificate for my domain `https://turbo-test.automation.cloud.ibm.com`, but I don't know where to set it up.
2. Even if I ignore the browser warning and accept the risk, the page doesn't direct  to the login page correctly and finally show error `The page isn’t redirecting properly` 

What should I do to make my own route work without any certificate warning from browser. Am I missing anything?
Thanks
